"""init

Revision ID: 12b3076691d8
Revises: 
Create Date: 2026-05-06 12:04:32.304116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b3076691d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('agent_used', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('reasoning_steps', sa.JSON(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=20), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('work_experience', sa.Integer(), nullable=True),
    sa.Column('current_job_title', sa.String(length=100), nullable=True),
    sa.Column('target_industry', sa.String(length=100), nullable=True),
    sa.Column('target_salary_min', sa.Float(), nullable=True),
    sa.Column('target_salary_max', sa.Float(), nullable=True),
    sa.Column('location_preference', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('analysis_history')
    op.drop_table('users')
    # ### end Alembic commands ###
