"""add agent_tasks

Revision ID: 1f232d078660
Revises: 5e52b9f83ca4
Create Date: 2026-06-22 15:58:24.028155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f232d078660'
down_revision = '5e52b9f83ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('last_agent', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_conversation', ['conversation_id'], unique=False)
        batch_op.create_index('idx_task_status', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_task_user', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_tasks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.create_index('idx_user_conversation', ['user_id', 'conversation_id'], unique=False)
        batch_op.create_index('idx_user_updated', ['user_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.create_index('idx_job_skill', ['job_id', 'skill_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_skills_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_skills_skill_name'), ['skill_name'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_city_salary', ['city', 'salary_avg'], unique=False)
        batch_op.create_index('idx_title_industry', ['title', 'industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_industry'))
        batch_op.drop_index(batch_op.f('ix_jobs_city'))
        batch_op.drop_index('idx_title_industry')
        batch_op.drop_index('idx_city_salary')

    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_skills_skill_name'))
        batch_op.drop_index(batch_op.f('ix_job_skills_job_id'))
        batch_op.drop_index('idx_job_skill')

    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_history_user_id'))
        batch_op.drop_index('idx_user_updated')
        batch_op.drop_index('idx_user_conversation')

    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_conversation_id'))
        batch_op.drop_index('idx_task_user')
        batch_op.drop_index('idx_task_status')
        batch_op.drop_index('idx_task_conversation')

    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
