"""add career profile fields

Revision ID: 5e52b9f83ca4
Revises: a02fe08d9616
Create Date: 2026-05-13 10:14:11.995834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e52b9f83ca4'
down_revision = 'a02fe08d9616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_search_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('work_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expected_join_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('company_type_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('available_hours_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('side_job_income_target', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('side_job_income_target')
        batch_op.drop_column('available_hours_per_week')
        batch_op.drop_column('certifications')
        batch_op.drop_column('projects')
        batch_op.drop_column('company_type_preference')
        batch_op.drop_column('expected_join_time')
        batch_op.drop_column('work_preference')
        batch_op.drop_column('job_search_status')

    # ### end Alembic commands ###
