"""add target_job_title to user_profiles

Revision ID: 76c0c50a9301
Revises: cd6ba1e8510d
Create Date: 2026-05-13 09:42:43.411209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c0c50a9301'
down_revision = 'cd6ba1e8510d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_job_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('target_job_title')

    # ### end Alembic commands ###
