"""add conversation support

Revision ID: 82bdb1af1a09
Revises: 12b3076691d8
Create Date: 2026-05-06 14:28:52.653039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bdb1af1a09'
down_revision = '12b3076691d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('messages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analysis_history_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_history_conversation_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('messages')
        batch_op.drop_column('title')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
