"""add target_jobs to user_profiles

Revision ID: a02fe08d9616
Revises: 76c0c50a9301
Create Date: 2026-05-13 10:04:41.455350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02fe08d9616'
down_revision = '76c0c50a9301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_jobs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('target_jobs')

    # ### end Alembic commands ###
